### ISSUE TITLE
Device not detected in Windows 10

### ISSUE THREAD

**Issue by imberium** [adafruit/Adafruit-Feather-M0-WiFi-WINC1500-PCB#1]
Hello,

I have an adafruit Feather M0 Wifi (ATWINC1500), but I didn't manage to detect it in my laptop running windows 10 . I have seen in the forum that this could be because of USB 3, do you think that this is the problem ?

**Comment by ladyada** [comment]
please post in the adafruit forums.adafruit.com - tech support is handled there! thx :)
